### ISSUE TITLE
upgrades crash game

### ISSUE THREAD

**Issue by BlockZapper** [lasgauti/AncientMonkey#25]
ace, heli and SOME 4th path upgrades, without a clear pattern, crash the game. Note that the 4th path upgrades that aren't a heli or ace only crash the game upon attacking. I have made a small list of the upgrades that I have noticed so far:

MONKEY ACE, LOTS MORE DARTS, QUAD DARTS, CRACK SHOT DARTS, OPERATION: DART STORM, DOGFIGHTER, RAILGUN, SKY SHREDDER, FLYING FORTRESS, FLYING DUTCHMAN, GOLIATH DOOMSHIP, DREADBLOON, CHAKRAMS, NINJA BLADE

EDIT: I have tried rolling back to as far as 2.3.0 of the mod, issue still seems to persist

**Comment by LolISkriptIsCool** [comment]
All monkey ace and helipilot upgrades crash the game

**Comment by LolISkriptIsCool** [comment]
and also all air things

**Comment by LolISkriptIsCool** [comment]
SOLUTION: Downgrade to melonloader version 0.61 and it will be fixed

**Comment by BlockZapper** [comment]
> SOLUTION: Downgrade to melonloader version 0.61 and it will be fixed

you legend, thank you

**Comment by LolISkriptIsCool** [comment]
why did u reopen

**Comment by BlockZapper** [comment]
> why did u reopen

figured that if someone else needed it they may perhaps look here instead of in closed issues, gonna close again now, mb
